# Generated by Django 3.1.7 on 2021-04-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('html', models.JSONField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scraper_api.pagerequest')),
            ],
        ),
    ]
