#build env
FROM python:3 as build
ENV PYTHONBUFFERED=1

WORKDIR /app

COPY scraper/requirements.txt /app/
RUN pip install -r requirements.txt

COPY scraper/ /app/

#prod env
FROM nginx:stable-alpine
#TODO Django as back end in Nginx
COPY --from=build /app/build /usr/share/nginx/
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]