FROM python:3
ENV PYTHONBUFFERED=1

WORKDIR /app
RUN adduser -D webwalker && chown -R webwalker /app

COPY back-django/requirements.txt /app/
RUN pip install -r requirements.txt

COPY back-django/ /app/

USER webwalker
CMD ["python", "manage.py", "runserver 0.0.0.0:8000"]