#build env
FROM python:3 as build
ENV PYTHONBUFFERED=1

WORKDIR /app
RUN adduser -D webwalker && chown -R webwalker /app

COPY back-django/requirements.txt /app/
RUN pip install -r requirements.txt

COPY back-django/ /app/

#prod env
FROM nginx:stable-alpine
#TODO Django as back end in Nginx
COPY --from=build /app/build /usr/share/nginx/
EXPOSE 80

USER webwalker
HEALTHCHECK CMD ["nginx", "-g", "daemon off;"]
