FROM python:3
ENV PYTHONBUFFERED=1

WORKDIR /app

COPY back-django/requirements.txt /app/
RUN pip install -r requirements.txt

COPY back-django/ /app/

CMD ["python", "manage.py", "runserver 0.0.0.0:8000"]