version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scraper-api
      - POSTGRES_USER=webwalker
      #TODO Password
      - POSTGRES_PASSWORD=test

  scraper:
    build: Dockerfile-scraper.prod
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  front:
    build: Dockerfile-front.prod
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true