name: Docker Image CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#TODO Dev builds push to DockerHub, tags
jobs:

  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile-back-django.prod, Dockerfile-front.prod]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: src/${{ matrix.dockerfile }}
        push: true
        context: ./src
        tags: arkko002/pywalker:latest
